version: "3"
services:
# Service: mc1
  mc1:
    image: 192.168.50.100:5000/project_x86_64
    deploy:
      placement:
        constraints: [node.hostname == hub]
      restart_policy:
        condition: none
    command: mctr ../cfg/MyExample.cfg
    

# Service: hc1
  hc1:
    image: 192.168.50.100:5000/project_armv7l
    deploy:
      placement:
        constraints: [node.hostname == pi-01]
      restart_policy:
        condition: none
    command: ./MyExample mc1 3000
    volumes:
      - /sys:/sys
      

# Service: hc2
  hc2:
    image: 192.168.50.100:5000/project_armv7l
    deploy:
      placement:
        constraints: [node.hostname == pi-02]
      restart_policy:
        condition: none
    command: ./MyExample mc1 3000
    volumes:
      - /sys:/sys
      


