ARG ARCH
FROM titan_${ARCH}

# Setup Project
COPY ./src/ /home/project/

RUN  cd /home/project/ && \
     ttcn3_makefilegen MyExample.ttcn GPIO_Pin_Port.cc GPIO_Pin_Port.hh GPIOPinPort.ttcn -f && \
     make

CMD  cd /home/project/ && \
#     ttcn3_start MyExample MyExample.cfg
     ./MyExample mc 3000
