version: "3"
services:
  mc:
    image: 192.168.50.100:5000/project_mc
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - hc1
      - hc2
  hc1:
    image: 192.168.50.100:5000/project_hc
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3
    depends_on:
      - mc
    deploy:
      placement:
        constraints: [node.role != manager]
  hc2:
    image: 192.168.50.100:5000/project_hc
    networks:
      mynetwork:
        ipv4_address: 172.18.0.4
    depends_on:
      - mc
    deploy:
      placement:
        constraints: [node.role != manager]

networks:
  mynetwork:
    
