ARG ARCH
FROM titan_${ARCH}

# Setup Project
COPY ./app/ /home/project/

RUN  cd /home/project/ && \
     ttcn3_makefilegen -t project.tpd -f && \
     cd ./bin/ && \
     make

CMD  cd /home/project/bin/ && \
#     ttcn3_start MyExample MyExample.cfg
     ./MyExample mc 3000
